### ISSUE TITLE
Retry using VS2019 or newer

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/vigra-feedstock#128]
About 1.5 years ago, be57b0f0476f92aae806b93b8ad9b31d5b83d825 went back to VS2017 due to some apparent issues at the time. It would be good to remove
https://github.com/conda-forge/vigra-feedstock/blob/5fba74712227c0425deaebe99e601a59fe8f1c76/recipe/conda_build_config.yaml#L1-L5

and just use the conda-forge default compilers, as vigra is among the last feedstocks in conda-forge to still use VS2017.

Hopefully vigra has become compatible with newer VS in the meantime... 🤞

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by hmaarrfk** [comment]
It seems we are still having errors with the latest version.

I remember I had tracked it down a bit, but never got to the bottom of it:
https://github.com/ukoethe/vigra/issues/525

**Comment by h-vetinari** [comment]
Thanks for checking!

**Comment by hmaarrfk** [comment]
this might be a compiler error. the iterator has a const and a non-const version. is there a newer compiler version? 2022??

**Comment by h-vetinari** [comment]
> is there a newer compiler version? 2022??

Yes, vs2022. Should be functional; if not, let us know on the vc-feedstock.

**Comment by hmaarrfk** [comment]
hmm ok lets try.

**Comment by h-vetinari** [comment]
Fixed by #131

**Comment by hmaarrfk** [comment]
but only in the sense that i gave up even more ;)

**Comment by h-vetinari** [comment]
Also in the sense that there's no more vs2017 components in the Azure images: https://github.com/conda-forge/vc-feedstock/issues/78

**Comment by hmaarrfk** [comment]
oh.... really lucky that I gave up at the right time!!!
