### ISSUE TITLE
so many patches that are in vigra master...

### ISSUE THREAD

**Issue by k-dominik** [conda-forge/vigra-feedstock#82]
The last vigra release was in 2017. There is not a lot of action on the repository, but some stuff has been fixed. Not all has been available as patches here in conda-forge and the list of patches that are there (stuff that is already merged on vigra master) is quite long. I can relate that no one wants to start maintaining a fork. Is there any way out of this mess?

**Comment by hmaarrfk** [comment]
I think this is something best expressed upstream.

isuruf once mentionned that adding a version date with a git hash might be an acceptable way forward for software that has never been released.

However, I would first try to communicate with upstream if you want to help them release
